In [67]:
import numpy as np
from numpy.linalg import inv, det, matrix_rank, norm
from scipy.linalg import eig

In [68]:
#Câu 1
def question1():
    A = np.array([2, -1, 3, 0])
    B = np.array([1, 4, -2, 5])
    C = np.array([[1, 2, -1], [0, 3, 4], [2, -1, 0]])

    A_plus_B = A + B
    expr = 3 * A - 2 * B
    dot_AB = np.dot(A, B)
    angle = np.degrees(np.arccos(dot_AB / (norm(A) * norm(B))))
    CTC = C.T @ C

    print("Câu 1:")
    print("  A + B             =", A_plus_B)
    print("  3A - 2B           =", expr)
    print("  A · B             =", dot_AB)
    print("  Góc giữa A và B   =", round(angle, 3), "độ")
    print("  C^T * C           =\n", CTC)


In [69]:
#Câu 2
def question2():
    M = np.array([[1, 2, 3, 0], [4, 5, 6, 1], [7, 8, 9, 2], [0, 1, 1, 0]])
    N = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

    MN = M @ N
    det_M = det(M)
    rank_N = matrix_rank(N)

    print("\nCâu 2:")
    print("  M * N             =\n", MN)
    print("  Định thức M       =", det_M)
    print("  Hạng của N        =", rank_N)


In [70]:
#Câu 3
def question3():
    P = np.array([[2, 1, 0, 1], [0, 3, 1, -1], [1, 0, 4, 2], [0, 1, 0, 3]])
    b_vec = np.array([4, 7, 9, 5])

    try:
        P_inv = inv(P)
        x_sol = P_inv @ b_vec
        Px_check = P @ x_sol
    except np.linalg.LinAlgError:
        P_inv = None
        x_sol = None
        Px_check = None

    print("\nCâu 3:")
    print("  Nghịch đảo P      =\n", P_inv)
    print("  Nghiệm hệ Px = b  =", x_sol)
    print("  Kiểm tra P*x      =", Px_check)


In [71]:
#Câu 4
def question4():
    Q = np.array([[4, -1, 0], [1, 3, -2], [0, 1, 2]])
    eigenvalues, eigenvectors = eig(Q)
    normalized_vectors = np.array([v / norm(v) for v in eigenvectors.T])

    print("\nCâu 4:")
    print("  Giá trị riêng     =", eigenvalues)
    print("  Vector riêng      =\n", eigenvectors)
    print("  Vector chuẩn hóa  =\n", normalized_vectors)


In [72]:
#Câu 5
def question5():
    R = np.array([[1, -2, 3], [2, 0, 1], [-1, 1, 4]])
    b5 = np.array([10, 8, 7])
    x5 = np.linalg.solve(R, b5)
    try:
        R_inv = inv(R)
        x5_by_inverse = R_inv @ b5
    except np.linalg.LinAlgError:
        R_inv = None
        x5_by_inverse = None
    fro_norm = norm(R, 'fro')
    print("\nCâu 5:")
    print("  Nghiệm Rx = b      =", x5)
    print("  Nghịch đảo R       =\n", R_inv)
    print("  Nghiệm bằng R^-1*b =", x5_by_inverse)
    print("  Chuẩn Frobenius    =", fro_norm)


In [77]:
question1()
question2()
question3()
question4()
question5()


Câu 1:
  A + B             = [3 3 1 5]
  3A - 2B           = [  4 -11  13 -10]
  A · B             = -8
  Góc giữa A và B   = 108.376 độ
  C^T * C           =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]

Câu 2:
  M * N             =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
  Định thức M       = 6.66133814775094e-16
  Hạng của N        = 2

Câu 3:
  Nghịch đảo P      =
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]
  Nghiệm hệ Px = b  = [0.46511628 2.10465116 1.65116279 0.96511628]
  Kiểm tra P*x      = [4. 7. 9. 5.]

Câu 4:
  Giá trị riêng     = [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
  Vector riêng      =
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+