In [1]:
import numpy as np
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
# a)
print("Câu 1a:")
print("A + B =", A + B)
print("2A + 3B =", 2*A + 3*B)
# b)
print("\nCâu 1b:")
dot_product = np.dot(A, B)
angle = np.degrees(np.arccos(dot_product / (np.linalg.norm(A) * np.linalg.norm(B))))
print("A · B =", dot_product)
print("Góc giữa A và B (độ) =", round(angle, 3))
# c)
print("\nCâu 1c:")
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])
CCT = np.dot(C, C.T)
print("C * C^T =\n", CCT)


Câu 1a:
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

Câu 1b:
A · B = -5
Góc giữa A và B (độ) = 99.594

Câu 1c:
C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [2]:
import numpy as np
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])
N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])
# a)
print("Câu 2a:\nM × N =\n", np.dot(M, N))
# b)
print("\nCâu 2b:")
try:
    print("Định thức M =", round(np.linalg.det(M), 3))
except:
    print("Không thể tính định thức M")
# c)
print("\nCâu 2c:")
print("Hạng của N =", np.linalg.matrix_rank(N))


Câu 2a:
M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

Câu 2b:
Định thức M = 409.0

Câu 2c:
Hạng của N = 4


In [3]:
import numpy as np
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])
# a)
print("Câu 3a:")
try:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo P⁻¹ =\n", P_inv)
except np.linalg.LinAlgError:
    print("P không khả nghịch")
# b)
print("\nCâu 3b:")
x = np.dot(P_inv, b)
print("Nghiệm x =", x)
# c)
print("\nCâu 3c:")
print("P @ x =", np.dot(P, x))
print("So với b  =", b)


Câu 3a:
Ma trận nghịch đảo P⁻¹ =
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]

Câu 3b:
Nghiệm x = [2.         1.71428571 0.42857143 0.85714286]

Câu 3c:
P @ x = [6. 8. 3. 7.]
So với b  = [6 8 3 7]


In [4]:
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])
eig_vals, eig_vecs = np.linalg.eig(Q)
print("Câu 4a:")
print("Giá trị riêng =", eig_vals)
print("\nCâu 4b:")
for i in range(len(eig_vals)):
    print(f"Vector riêng ứng với λ={eig_vals[i]:.3f}: {eig_vecs[:, i]}")
print("\nCâu 4c:")
for i in range(len(eig_vals)):
    normed = eig_vecs[:, i] / np.linalg.norm(eig_vecs[:, i])
    print(f"Vector riêng chuẩn hóa v{i+1} =", normed)


Câu 4a:
Giá trị riêng = [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]

Câu 4b:
Vector riêng ứng với λ=6.355+0.000j: [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng ứng với λ=2.822+1.077j: [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng ứng với λ=2.822-1.077j: [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]

Câu 4c:
Vector riêng chuẩn hóa v1 = [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng chuẩn hóa v2 = [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng chuẩn hóa v3 = [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]


In [5]:
import numpy as n
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])
# a)
print("Câu 5a:")
x = np.linalg.solve(R, b)
print("Nghiệm x =", x)
# b)
print("\nCâu 5b:")
try:
    R_inv = np.linalg.inv(R)
    x_check = np.dot(R_inv, b)
    print("R khả nghịch, R⁻¹ =\n", R_inv)
    print("Giải lại x =", x_check)
except np.linalg.LinAlgError:
    print("R không khả nghịch")
# c)
print("\nCâu 5c:")
fro = np.linalg.norm(R, ord='fro')
print("Chuẩn Frobenius của R =", round(fro, 3))


Câu 5a:
Nghiệm x = [2.78823529 1.52941176 1.18823529]

Câu 5b:
R khả nghịch, R⁻¹ =
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Giải lại x = [2.78823529 1.52941176 1.18823529]

Câu 5c:
Chuẩn Frobenius của R = 8.0
